
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL = "https://github.com/MehVahdJukaar/moyai/issues"

[[mods]] #mandatory

    modUrl = "https://www.curseforge.com/minecraft/mc-mods/moyai"

    modId="moyai" #mandatory

    version = "${version}"

    displayName="Moyai" #mandatory

    logoFile="icon.png" #optional

    credits="MehVahdJukaar, Plantkillable" #optional

    authors="MehVahdJukaar" #optional

    description='''
         *vine boom*
         🗿🗿🗿
    '''

[modproperties.moyai]
    catalogueItemIcon="moyai:moyai"
    configuredBackground = "minecraft:textures/block/tuff.png"

[[dependencies.moyai]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.moyai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moyai]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.0.16,]"
    ordering="AFTER"
    side="BOTH"
